modLoader="javafml"
loaderVersion="[47,)"
license="APACHE-2.0"
issueTrackerURL="https://github.com/noeppi-noeppi/MythicBotany/issues"

[[mods]]
modId="mythicbotany"
version="${version}"
displayName="MythicBotany"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mythicbotany"
updateJSONURL="https://assets.melanx.de/updates/mythicbotany.json"
authors="noeppi_noeppi, Contributors: MelanX"
description='''
Dive deeper into the world of botania.
'''


[[dependencies.mythicbotany]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="libx"
    mandatory=true
    versionRange="[1.20.1-5.0.12,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="botania"
    mandatory=true
    versionRange="[1.20.1-443,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.20.1-84,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="curios"
    mandatory=true
    versionRange="[5.5.0+1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="jei"
    mandatory=false
    versionRange="[1.20.1-15.2.0.27,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.mythicbotany]]
    modId="apotheosis"
    mandatory=false
    versionRange="[7.4.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicbotany]]
    modId="botanicadds"
    mandatory=false
    versionRange="[20.1.3,)"
    ordering="NONE"
    side="BOTH"
